version: '3'

services:

  flask_app:
    restart: always
    build:
      context : ./
      dockerfile : ./flask_app/Dockerfile
    ports:
      - "8000:8000"
    command: python wsgi.py

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app

  db_server:
    image: yandex/clickhouse-server:21.8
    volumes:
      - ./database/db_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
  
#  scraper_worker:
#    build: ./pokemon_data_scraper
#    volumes:
#      - ./pokemon_data_scraper:/deploy/pokemon_data_scraper
#